project:
  type: website
  output-dir: docs

website:
  title: "Devan Nightly"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: [minty, smaller_lists.scss]
    css: styles.css
